In [46]:
from SpinTools.spinhamiltonian import spinhamiltonian as sh
import numpy as np
from scipy.constants import physical_constants as spc
from scipy.constants import constants as sc
import itertools

h = spc["Planck constant"][0]

ham = sh.SpinHamiltonian("Tst")

In [47]:
def decorator(gamma_function):
    def wrapper_function(*args,**kwargs):
        return gamma_function(*args,**kwargs)
    return wrapper_function

@decorator
def zeeman(Bz):
    return ham.electron_zeeman([0,0,Bz]) + ham.nuclear_zeeman([0,0,Bz])

@decorator
def gamma(row,eigvec,hdrive):
    return list(map(lambda col : 1e24*abs(np.matmul(eigvec[:,col].conjugate(), 
                np.matmul(hdrive,eigvec[:,row]))), range(row+1,len(eigvec))))

@decorator
def hamiltonian(Bz):
    return ham.get_hamiltonian([0,0,Bz]) / h / 1e09
#     return ham.hyperfine()

@decorator
def estate(H):
    return np.linalg.eig(H)

@decorator
def E(evals):
    return evals[1] - evals[0]

def get_gamma_values(gam):
    gam = np.array([x for x in gam for x in x])
    gam = list(itertools.chain.from_iterable(gam))
    return list(filter(lambda a: a != 0, gam))

In [48]:
b = np.arange(0,1,0.5)

H = list(map(hamiltonian,b)) # Get spin hamiltonian
Hds = zeeman(1) # Get perturbation hamiltonian

evecs = [np.linalg.eig(H)[1][i] for i in range(len(b))]

# np.set_printoptions(suppress=False,precision=1)
# print(np.real(H))
# print('\n')
# print(np.linalg.eig(H[0])[0])
# print('\n')
# print(np.linalg.eig(H[0])[1])
# print('\n')
# print(np.linalg.eig(H[1])[0])
# print('\n')
# print(np.linalg.eig(H[1])[1])

# e = list(map(estate,H)) # get eigenstates

# Get transition rate
# gam = [[gamma(i,e[k][1],Hds) for i in range(len(Hds[0]))] for k in range(len(b))]

# Flatten transition rates and give only the values
# gam = get_gamma_values(gam)

## Get eigenvalues for each matrix element
# evals = [e[i][0] for i in range(len(b))]
# energy = [abs(evals[i][1] - evals[i][0]) for i in range(len(b))]

In [30]:
np.set_printoptions(suppress=False, precision=3)
print(np.real(evecs[1][:,0]))

[-0.    -0.    -0.    -0.    -0.    -0.    -0.    -0.    -0.    -0.248
 -0.    -0.    -0.    -0.    -0.    -0.    -0.    -0.     0.969 -0.   ]


In [40]:
for n in range(len(b)):
    for m in range(len(Hds)-1):
#         print(1e24*abs(np.matmul(evecs[n][:,m+1].conjugate(),np.matmul(Hds,evecs[n][:,m]))))
        print('{}, {}'.format(m+1,m))

1, 0
2, 1
3, 2
4, 3
5, 4
6, 5
7, 6
8, 7
9, 8
10, 9
11, 10
12, 11
13, 12
14, 13
15, 14
16, 15
17, 16
18, 17
19, 18
1, 0
2, 1
3, 2
4, 3
5, 4
6, 5
7, 6
8, 7
9, 8
10, 9
11, 10
12, 11
13, 12
14, 13
15, 14
16, 15
17, 16
18, 17
19, 18


In [36]:
np.shape(Hds)

(20, 20)

In [49]:
E0_values = np.linalg.eig(H[0])[0]
E0_vecs = np.linalg.eig(H[0])[1]

E1_values = np.linalg.eig(H[1])[0]
E1_vecs = np.linalg.eig(H[1])[1]

print(E0_vecs)

[[-0. -0.j -0. -0.j -0. -0.j -0. -0.j  0. +0.j -0. -0.j  1. +0.j  0. +0.j]
 [-0. -0.j -0. -0.j  0.5-0.j  0.9+0.j  0. +0.j -0. -0.j  0. +0.j  0. +0.j]
 [-0. -0.j -0. -0.j  0.9+0.j -0.5-0.j  0. +0.j -0. -0.j  0. +0.j  0. +0.j]
 [-0. -0.j -0. -0.j -0. -0.j -0. -0.j  0.7+0.j -0.7-0.j  0. +0.j  0. +0.j]
 [-0. -0.j -0. -0.j -0. -0.j -0. -0.j  0.7+0.j  0.7+0.j  0. +0.j  0. +0.j]
 [-0.5-0.j  0.9+0.j -0. -0.j -0. -0.j  0. +0.j -0. -0.j  0. +0.j  0. +0.j]
 [ 0.9+0.j  0.5-0.j -0. -0.j -0. -0.j  0. +0.j -0. -0.j  0. +0.j  0. +0.j]
 [-0. -0.j -0. -0.j -0. -0.j -0. -0.j  0. +0.j -0. -0.j  0. +0.j  1. +0.j]]


### i = 1st col

In [37]:
print(np.matmul(E0_vecs[:,1].conjugate(),np.matmul(Hds,E0_vecs[:,0])))
print(np.matmul(E0_vecs[:,2].conjugate(),np.matmul(Hds,E0_vecs[:,0])))
print(np.matmul(E0_vecs[:,3].conjugate(),np.matmul(Hds,E0_vecs[:,0])))
print(np.matmul(E0_vecs[:,4].conjugate(),np.matmul(Hds,E0_vecs[:,0])))
print(np.matmul(E0_vecs[:,5].conjugate(),np.matmul(Hds,E0_vecs[:,0])))
print(np.matmul(E0_vecs[:,6].conjugate(),np.matmul(Hds,E0_vecs[:,0])))
print(np.matmul(E0_vecs[:,7].conjugate(),np.matmul(Hds,E0_vecs[:,0])))

(-8.023506730198696e-24+0j)
0j
(8.023506730198696e-24+0j)
0j
(2.7803470404968016e-23+0j)
0j
0j


### i = 2nd col

In [39]:
print(np.matmul(E0_vecs[:,2].conjugate(),np.matmul(Hds,E0_vecs[:,1])))
print(np.matmul(E0_vecs[:,3].conjugate(),np.matmul(Hds,E0_vecs[:,1])))
print(np.matmul(E0_vecs[:,4].conjugate(),np.matmul(Hds,E0_vecs[:,1])))
print(np.matmul(E0_vecs[:,5].conjugate(),np.matmul(Hds,E0_vecs[:,1])))
print(np.matmul(E0_vecs[:,6].conjugate(),np.matmul(Hds,E0_vecs[:,1])))
print(np.matmul(E0_vecs[:,7].conjugate(),np.matmul(Hds,E0_vecs[:,1])))

0j
0j
0j
0j
0j
0j


### i = 3rd col

In [41]:
print(np.matmul(E0_vecs[:,3].conjugate(),np.matmul(Hds,E0_vecs[:,2])))
print(np.matmul(E0_vecs[:,4].conjugate(),np.matmul(Hds,E0_vecs[:,2])))
print(np.matmul(E0_vecs[:,5].conjugate(),np.matmul(Hds,E0_vecs[:,2])))
print(np.matmul(E0_vecs[:,6].conjugate(),np.matmul(Hds,E0_vecs[:,2])))
print(np.matmul(E0_vecs[:,7].conjugate(),np.matmul(Hds,E0_vecs[:,2])))

(8.023506730198696e-24+0j)
0j
0j
0j
0j


### i = 4th col

In [46]:
print(np.matmul(E0_vecs[:,4].conjugate(),np.matmul(Hds,E0_vecs[:,3])))
print(np.matmul(E0_vecs[:,5].conjugate(),np.matmul(Hds,E0_vecs[:,3])))
print(np.matmul(E0_vecs[:,6].conjugate(),np.matmul(Hds,E0_vecs[:,3])))
print(np.matmul(E0_vecs[:,7].conjugate(),np.matmul(Hds,E0_vecs[:,3])))

0j
0j
0j
0j


### i = 5th col

In [47]:
print(np.matmul(E0_vecs[:,5].conjugate(),np.matmul(Hds,E0_vecs[:,4])))
print(np.matmul(E0_vecs[:,6].conjugate(),np.matmul(Hds,E0_vecs[:,4])))
print(np.matmul(E0_vecs[:,7].conjugate(),np.matmul(Hds,E0_vecs[:,4])))

(2.7803470404968016e-23+0j)
0j
0j


### i = 6th col

In [44]:
print(np.matmul(E0_vecs[:,6].conjugate(),np.matmul(Hds,E0_vecs[:,5])))
print(np.matmul(E0_vecs[:,7].conjugate(),np.matmul(Hds,E0_vecs[:,5])))

0j
0j


### i = 7th col

In [48]:
print(np.matmul(E0_vecs[:,7].conjugate(),np.matmul(Hds,E0_vecs[:,6])))

0j


In [50]:
print(np.matmul(E1_vecs[:,1].conjugate(),np.matmul(Hds,E1_vecs[:,0])))
print(np.matmul(E1_vecs[:,2].conjugate(),np.matmul(Hds,E1_vecs[:,0])))
print(np.matmul(E1_vecs[:,3].conjugate(),np.matmul(Hds,E1_vecs[:,0])))
print(np.matmul(E1_vecs[:,4].conjugate(),np.matmul(Hds,E1_vecs[:,0])))
print(np.matmul(E1_vecs[:,5].conjugate(),np.matmul(Hds,E1_vecs[:,0])))
print(np.matmul(E1_vecs[:,6].conjugate(),np.matmul(Hds,E1_vecs[:,0])))
print(np.matmul(E1_vecs[:,7].conjugate(),np.matmul(Hds,E1_vecs[:,0])))

(-1.3374724896606492e-25+0j)
0j
0j
0j
0j
0j
0j


In [51]:
print(np.matmul(E1_vecs[:,2].conjugate(),np.matmul(Hds,E1_vecs[:,1])))
print(np.matmul(E1_vecs[:,3].conjugate(),np.matmul(Hds,E1_vecs[:,1])))
print(np.matmul(E1_vecs[:,4].conjugate(),np.matmul(Hds,E1_vecs[:,1])))
print(np.matmul(E1_vecs[:,5].conjugate(),np.matmul(Hds,E1_vecs[:,1])))
print(np.matmul(E1_vecs[:,6].conjugate(),np.matmul(Hds,E1_vecs[:,1])))
print(np.matmul(E1_vecs[:,7].conjugate(),np.matmul(Hds,E1_vecs[:,1])))

0j
0j
0j
0j
0j
0j


In [52]:
print(np.matmul(E1_vecs[:,3].conjugate(),np.matmul(Hds,E1_vecs[:,2])))
print(np.matmul(E1_vecs[:,4].conjugate(),np.matmul(Hds,E1_vecs[:,2])))
print(np.matmul(E1_vecs[:,5].conjugate(),np.matmul(Hds,E1_vecs[:,2])))
print(np.matmul(E1_vecs[:,6].conjugate(),np.matmul(Hds,E1_vecs[:,2])))
print(np.matmul(E1_vecs[:,7].conjugate(),np.matmul(Hds,E1_vecs[:,2])))

(-1.3601428877085969e-25+0j)
0j
0j
0j
0j


In [53]:
print(np.matmul(E1_vecs[:,4].conjugate(),np.matmul(Hds,E1_vecs[:,3])))
print(np.matmul(E1_vecs[:,5].conjugate(),np.matmul(Hds,E1_vecs[:,3])))
print(np.matmul(E1_vecs[:,6].conjugate(),np.matmul(Hds,E1_vecs[:,3])))
print(np.matmul(E1_vecs[:,7].conjugate(),np.matmul(Hds,E1_vecs[:,3])))

0j
0j
0j
0j


In [54]:
print(np.matmul(E1_vecs[:,5].conjugate(),np.matmul(Hds,E1_vecs[:,4])))
print(np.matmul(E1_vecs[:,6].conjugate(),np.matmul(Hds,E1_vecs[:,4])))
print(np.matmul(E1_vecs[:,7].conjugate(),np.matmul(Hds,E1_vecs[:,4])))

(-1.5574995855816112e-25+0j)
0j
0j


In [55]:
print(np.matmul(E1_vecs[:,6].conjugate(),np.matmul(Hds,E1_vecs[:,5])))
print(np.matmul(E1_vecs[:,7].conjugate(),np.matmul(Hds,E1_vecs[:,5])))

0j
0j


In [56]:
print(np.matmul(E1_vecs[:,7].conjugate(),np.matmul(Hds,E1_vecs[:,6])))

0j


In [41]:
x = np.arange(10)
np.roll(x,2)

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [42]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
[0,1,2,3,4,5,6,7]

[0] [1,2,3,4,5,6,7]
[1] [2,3,4,5,6,7]
[2] [3,4,5,6,7]
[3] [4,5,6,7]
[4] [5,6,7]
[5] [6,7]
[6] [7]

TypeError: list indices must be integers or slices, not tuple

In [49]:
gam = lambda i,f : 1e24*abs(np.matmul(f.conjugate(), np.matmul(Hds,i)))

eiter = [[(y,z) for z in range(y+1,len(Hds))] for y in range(len(b))]
eiter = list(itertools.chain.from_iterable(eiter))
eiter

In [59]:
[gam(evecs[0][:,n],evecs[0][:,0]) for n in range(1,len(Hds))]
# [gam(evecs[0][:,n],evecs[0][:,1]) for n in range(2,len(Hds))]
# [gam(evecs[0][:,n],evecs[0][:,2]) for n in range(3,len(Hds))]
# [gam(evecs[0][:,n],evecs[0][:,3]) for n in range(4,len(Hds))]
# [gam(evecs[0][:,n],evecs[0][:,4]) for n in range(5,len(Hds))]
# [gam(evecs[0][:,n],evecs[0][:,5]) for n in range(6,len(Hds))]
# [gam(evecs[0][:,n],evecs[0][:,6]) for n in range(7,len(Hds))]


[8.023506730198696, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [125]:
ev = lambda evec,m : evec[:,m].conjugate()
list(map(ev,zip(evecs[0],1)))

TypeError: zip argument #2 must support iteration

In [113]:
evecs[0][eiter[0][1]]

array([-0.       -0.j, -0.       -0.j,  0.5      -0.j,  0.8660254+0.j,
        0.       +0.j, -0.       -0.j,  0.       +0.j,  0.       +0.j])

In [116]:
ev

<function __main__.<lambda>(evec, m)>